#include <stdio.h>

// yyparse is generated by Bison
extern int yyparse();

int main() {
    printf("Enter C code for compilation (end with Ctrl+D or Ctrl+Z):\n");
    if (yyparse() == 0) {
        printf("Parsing completed successfully.\n");
    } else {
        printf("Parsing failed due to syntax/semantic errors.\n");
    }
    return 0;
}

